// DEPRECATED (Phase-4 A2 surgery, 2026-05-27): NO LONGER THE SOURCE OF TRUTH.
// The Voynich seed is now authored by hand at apps/viewer/src/voynich.ts (real Yale IIIF AObject[] +
// the readings/sections/AV data, per docs/exhibits/voynich-rewrite/04-design.md). This script targeted
// the old `/voynich/*.{png,jpg}` local fixture + the VoynichObject/VoynichNote mini-schema, both retired.
// It will OVERWRITE the hand-authored seed if re-run — do not run it. Kept only as the historical record
// of how the original 5-folio fixture was imported.
//
// ONE-TIME import: the anvil "voynich-manuscript" fixture → Archie sample data.
// Reads the anvil project (.anvil/project.json + annotations/*.json), converts each annotation
// (SvgSelector polygon → xywh rect; "describing" body → a commenting note), parses real pixel
// dimensions from the image headers, copies the images into both apps' public/voynich/, and emits
// an identical `voynich.ts` data module into each app's src/. Re-run: `node scripts/import-voynich.mjs`.
// Not a reusable in-app importer — there is exactly one fixture (per the user), so this stays a script.
import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ARCHIE = join(dirname(fileURLToPath(import.meta.url)), "..");
const FIX = join(ARCHIE, "../anvil/app/public/fixture/voynich-manuscript");

// --- image dimensions from file headers (no deps) ---
function pngDims(b) { return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) }; }
function jpegDims(b) {
  let o = 2;
  while (o < b.length) {
    if (b[o] !== 0xff) { o++; continue; }
    const marker = b[o + 1];
    // SOF0..SOF15 carry the frame dimensions (skip DHT=C4, JPG=C8, DAC=CC).
    if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc) {
      return { h: b.readUInt16BE(o + 5), w: b.readUInt16BE(o + 7) };
    }
    o += 2 + b.readUInt16BE(o + 2); // skip this segment
  }
  throw new Error("no JPEG SOF marker");
}
function imageDims(path) {
  const b = readFileSync(path);
  if (b[0] === 0x89 && b[1] === 0x50) return pngDims(b);
  return jpegDims(b);
}

// --- SvgSelector polygon → bounding [x,y,w,h]; tolerate a FragmentSelector too ---
function selectorToRect(sel) {
  if (sel.type === "SvgSelector") {
    const pts = [...sel.value.matchAll(/(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/g)].map((m) => [parseFloat(m[1]), parseFloat(m[2])]);
    const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
    const x = Math.min(...xs), y = Math.min(...ys);
    return [Math.round(x), Math.round(y), Math.round(Math.max(...xs) - x), Math.round(Math.max(...ys) - y)];
  }
  if (sel.type === "FragmentSelector") {
    const m = sel.value.match(/xywh=(?:pixel:)?(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/);
    if (m) return [Math.round(+m[1]), Math.round(+m[2]), Math.round(+m[3]), Math.round(+m[4])];
  }
  throw new Error("unsupported selector " + sel.type);
}

const LABELS = {
  "article.png": "The cipher", "cosmological.jpg": "Cosmological folio", "herbal.jpg": "Herbal folio",
  "balneological.jpg": "Balneological folio", "script.jpg": "Voynichese script",
};

const project = JSON.parse(readFileSync(join(FIX, ".anvil/project.json"), "utf8"));
const credits = (readFileSync(join(FIX, "config.toml"), "utf8").match(/attribution\s*=\s*"([^"]+)"/) || [])[1] ?? "";

const objects = [];
const hashToObj = {};
project.images.forEach((im, i) => {
  const id = `o${i + 1}`;
  hashToObj[im.hash] = id;
  const { w, h } = imageDims(join(FIX, "images", im.file));
  objects.push({ id, source: `/voynich/${im.file}`, label: LABELS[im.file] ?? im.file, width: w, height: h });
  for (const app of ["viewer", "studio"]) {
    const dest = join(ARCHIE, "apps", app, "public", "voynich");
    if (!existsSync(dest)) mkdirSync(dest, { recursive: true });
    copyFileSync(join(FIX, "images", im.file), join(dest, im.file));
  }
});

const notes = [];
for (const im of project.images) {
  const page = JSON.parse(readFileSync(join(FIX, "annotations", `${im.hash}.json`), "utf8"));
  for (const it of page.items ?? []) {
    const objectId = hashToObj[(it.target.source || "").replace("urn:anvil:image:", "")];
    if (!objectId) continue;
    const bodies = Array.isArray(it.body) ? it.body : [it.body];
    const tb = bodies.find((b) => b && b.type === "TextualBody");
    const comment = (tb?.value ?? "").trim(); // keep markdown — rendered via renderMarkdown on display
    notes.push({ objectId, region: selectorToRect(it.target.selector), comment });
  }
}

const out = `// GENERATED by scripts/import-voynich.mjs — one-time import of the anvil voynich-manuscript
// fixture (Beinecke MS 408). Note bodies are markdown — render via @render/svelte renderMarkdown.
// Do not edit by hand; re-run the script to regenerate.
export interface VoynichObject { id: string; source: string; label: string; width: number; height: number; }
export interface VoynichNote { objectId: string; region: [number, number, number, number]; comment: string; }
export const voynichTitle = ${JSON.stringify(project.title)};
export const voynichCredits = ${JSON.stringify(credits)};
export const voynichObjects: VoynichObject[] = ${JSON.stringify(objects, null, 2)};
export const voynichNotes: VoynichNote[] = ${JSON.stringify(notes, null, 2)};
`;

for (const app of ["viewer", "studio"]) writeFileSync(join(ARCHIE, "apps", app, "src", "voynich.ts"), out);
console.log(`Imported ${objects.length} objects, ${notes.length} notes. Dims:`, objects.map((o) => `${o.label} ${o.width}x${o.height}`).join(", "));
