// ONE-TIME import: the REAL "Techno-Futures from Bidar" annotated map (COMPOST Issue 01, Micah Alex)
// → Archie. Source: one.compost.digital's OpenSeadragon viewer — map image /micah/nb-v24.jpg +
// /micah/micahsMapAnnotations.json (25 annotations, each {x,y,r,text,media[]} in MAP PIXELS).
// Converts each circle (center x,y radius r) → an Archie xywh rect (its bounding box), the real text
// → the note body, and image/audio media → appended markdown (renders in a markdown reader). Emits
// apps/studio/src/bidar.ts. The map + assets stay hosted on compost (external URLs). Re-run: node scripts/import-bidar.mjs
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SITE = "https://one.compost.digital/";
const MAP_URL = `${SITE}micah/nb-v24.jpg`;
const ANNS_URL = `${SITE}micah/micahsMapAnnotations.json`;
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTS = ["studio", "viewer"].map((app) => join(ROOT, "apps", app, "src", "bidar.ts"));

function jpegDims(buf) {
  let o = 2;
  while (o < buf.length) {
    if (buf[o] !== 0xff) { o++; continue; }
    const m = buf[o + 1];
    if (m >= 0xc0 && m <= 0xcf && m !== 0xc4 && m !== 0xc8 && m !== 0xcc) return { h: (buf[o + 5] << 8) | buf[o + 6], w: (buf[o + 7] << 8) | buf[o + 8] };
    o += 2 + ((buf[o + 2] << 8) | buf[o + 3]);
  }
  throw new Error("no SOF");
}

const anns = await (await fetch(ANNS_URL)).json();
const { w, h } = jpegDims(new Uint8Array(await (await fetch(MAP_URL)).arrayBuffer()));

// COMPOST's viewer (js/micah.js) authored coords in a 1920×1358 reference space and places markers
// at OSD viewport (x/1920, 0.7*y/1358); OSD maps viewport→image pixels by the image WIDTH. So the
// real nb-v24 pixel coords are: px = (x/1920)*w, py = (0.7*y/1358)*w, radius = (r/1920)*w.
const REF_W = 1920, REF_H = 1358, Y_FUDGE = 0.7;
const toPx = (v, ref) => (v / ref) * w;

const notes = anns.map((a) => {
  const cx = toPx(a.x, REF_W);
  const cy = (Y_FUDGE * a.y / REF_H) * w;
  const pr = toPx(a.r, REF_W);
  const x = Math.max(0, Math.round(cx - pr));
  const y = Math.max(0, Math.round(cy - pr));
  const wd = Math.round(pr * 2);
  const media = (a.media ?? []).map((m) =>
    m.type === "image" ? `\n\n![](${SITE}${m.url})` : m.type === "audio" ? `\n\n[♪ audio](${SITE}${m.url})` : "",
  ).join("");
  return { region: [x, y, wd, wd], comment: (a.text ?? "").trim() + media };
});

const out = `// GENERATED by scripts/import-bidar.mjs — the REAL "Techno-Futures from Bidar" annotated map
// (COMPOST Issue 01, Micah Alex). Map + assets hosted on one.compost.digital (external URLs).
// 25 annotations converted from circles (x,y,r in map pixels) to xywh rects; media → markdown.
// Do not edit by hand; re-run the script to regenerate.
export interface BidarNote { region: [number, number, number, number]; comment: string }

export const bidarTitle = "Techno-Futures from Bidar";
export const bidarObject = {
  id: "o1",
  source: ${JSON.stringify(MAP_URL)},
  label: "A condensed map of the Bidar mesh",
  width: ${w},
  height: ${h},
};

export const bidarNotes: BidarNote[] = ${JSON.stringify(notes, null, 2)};
`;

for (const o of OUTS) writeFileSync(o, out);
console.log(`Imported ${notes.length} annotations onto the ${w}x${h} map → ${OUTS.join(", ")}`);
