#!/usr/bin/env node
// Generates docs/TRACKERS.md — the Issue-N ↔ Archie-xxxx ↔ Q-N rosetta.
// Deterministic (no dates) so doclint can regenerate-and-diff it like hubs/INDEX.md.
// Usage: node scripts/trackers-gen.mjs           write docs/TRACKERS.md
//        node scripts/trackers-gen.mjs --stdout  print (doclint's drift check)
// Hand corrections live BELOW the marker line and are preserved on rewrite.

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MARKER = "<!-- hand-corrections below this line are preserved by scripts/trackers-gen.mjs -->";

const issuesMd = [...readFileSync(join(ROOT, "ISSUES.md"), "utf8").matchAll(/^## (Issue \d+) — (.+?)(?:\s*`|$)/gm)]
  .map((m) => [m[1], m[2]]);

const seeds = {};
for (const line of readFileSync(join(ROOT, ".seeds/issues.jsonl"), "utf8").split("\n")) {
  if (!line.trim()) continue;
  try {
    const j = JSON.parse(line);
    seeds[j.id] = `${j.title ?? ""} ${(j.description ?? "").slice(0, 2000)}`;
  } catch { /* torn line is sd's problem */ }
}
const citing = (re) => Object.keys(seeds).filter((id) => re.test(seeds[id])).sort();

const qfirst = new Map();
for (const f of readdirSync(join(ROOT, "docs/decisions")).filter((f) => f.endsWith(".md")).sort()) {
  readFileSync(join(ROOT, "docs/decisions", f), "utf8").split("\n").forEach((l, i) => {
    for (const q of l.match(/\bQ-\d+\b/g) ?? []) if (!qfirst.has(q)) qfirst.set(q, `docs/decisions/${f}:${i + 1}`);
  });
}

const lines = [
  "# TRACKERS — cross-tracker rosetta",
  "",
  "GENERATED by `node scripts/trackers-gen.mjs` — regenerate, don't hand-edit above the marker.",
  "Three id spaces: `Issue N` (ISSUES.md, FROZEN), `Archie-xxxx` (.seeds, canonical), `Q-N` (docs/decisions).",
  "",
  "## ISSUES.md → seeds",
  "",
  "| ISSUES.md | title | seeds tickets citing it |",
  "| --- | --- | --- |",
  ...issuesMd.map(([iid, title]) => {
    const hits = citing(new RegExp(`\\b${iid}\\b`)).join(", ") || "UNMAPPED";
    return `| ${iid} | ${title.slice(0, 60)} | ${hits} |`;
  }),
  "",
  "## Q-numbers → home + seeds",
  "",
  "| Q | defined | seeds tickets citing it |",
  "| --- | --- | --- |",
  ...[...qfirst.keys()].sort((a, b) => +a.slice(2) - +b.slice(2)).map((q) => {
    const hits = citing(new RegExp(`\\b${q}\\b`)).join(", ") || "—";
    return `| ${q} | ${qfirst.get(q)} | ${hits} |`;
  }),
  "",
  MARKER,
];

const target = join(ROOT, "docs/TRACKERS.md");
let tail = "";
try {
  const cur = readFileSync(target, "utf8");
  const i = cur.indexOf(MARKER);
  if (i >= 0) tail = cur.slice(i + MARKER.length);
} catch { /* first run */ }

const out = lines.join("\n") + (tail || "\n");
if (process.argv.includes("--stdout")) process.stdout.write(out);
else { writeFileSync(target, out); console.log(`wrote docs/TRACKERS.md (${issuesMd.length} issues, ${qfirst.size} Q)`); }
