// TIFF → WebP transcode for ingest (docs/research/browser-storage-quota.md, follow-up 3).
//
// Browsers ship NO TIFF decoder: a `.tif` admitted by folder-import's EXT_MIME passed the `image/*`
// gate and then died in createImageBitmap — 375 files silently tallied as failed in the Gawan Museum
// import. This module closes the gap AND the storage cost in one move: decode via UTIF (utif2, the
// maintained fork jimp uses — pure JS, ~30 KB, lazy-loaded so non-TIFF imports never pay for it),
// re-encode through the same canvas idiom as bake.ts. Measured on real digitization masters, an LZW
// TIFF lands 8–15× smaller as WebP at visually-equivalent quality.
//
// Prior art (per project rule): Tropy decodes TIFF with sharp/libvips natively; wasm-vips is the
// browser build of the same engine. UTIF was chosen over wasm-vips for footprint — the multi-MB WASM
// payload buys exotic-TIFF coverage (CMYK, tiled pyramids) the Gawan-class corpus doesn't need. If
// such files show up, swap THIS module's decode; the ingest seam stays.
//
// Browser-only (canvas), like bake.ts — verified in the browser, not headless. Throws on bytes UTIF
// can't parse; the caller's decode-phase catch classifies that as the "undecodable" refusal.
import { fitWithin } from "@render/core";

/** MIME strings the transcode owns. folder-import's EXT_MIME maps .tif/.tiff to "image/tiff"; a
 *  platform that types the file itself may report the legacy "image/x-tiff". */
export function isTiffMime(mime: string): boolean {
  return mime === "image/tiff" || mime === "image/x-tiff";
}

export interface TranscodedTiff {
  blob: Blob;
  width: number;
  height: number;
}

/** Decode `bytes` as TIFF and re-encode as a WebP display master, capped to `maxDim` on the longer
 *  edge (aspect-preserving, downscale-only — same contract as bakeDisplayMaster). Multi-page TIFFs
 *  (embedded thumbnails, scan strips) use the largest page: that's the master; page thumbnails are
 *  regenerated by the normal bakeThumbnail step downstream. */
export async function transcodeTiff(bytes: ArrayBuffer, maxDim: number, quality = 0.92): Promise<TranscodedTiff> {
  const UTIF = (await import("utif2")).default; // lazy: the decoder loads on the FIRST tiff, not at boot
  const ifds = UTIF.decode(bytes);
  if (ifds.length === 0) throw new Error("UTIF found no IFDs — not a decodable TIFF");
  // Largest page by pixel count. UTIF's IFD is a tag bag ("tXYZ" keys, readable BEFORE decodeImage):
  // t256 = ImageWidth, t257 = ImageLength per the TIFF 6 spec.
  const px = (p: (typeof ifds)[number]) => {
    const tag = (k: string) => { const v = p[k]; return Array.isArray(v) ? Number(v[0]) : 0; };
    return tag("t256") * tag("t257");
  };
  const page = ifds.reduce((a, b) => (px(b) > px(a) ? b : a));
  UTIF.decodeImage(bytes, page);
  const width = page.width, height = page.height;
  if (!width || !height) throw new Error("TIFF page decoded to zero dimensions");
  // Whole-page RGBA in memory (w*h*4 bytes) is this path's ceiling — a 6000px-edge scan is ~100 MB
  // transient, in line with the §80 display-master budget. The cap applies at DRAW, below.
  const rgba = UTIF.toRGBA8(page);

  const src = document.createElement("canvas");
  src.width = width;
  src.height = height;
  const srcCtx = src.getContext("2d");
  if (!srcCtx) throw new Error("2D canvas context unavailable for TIFF transcode");
  // Copy, not a view: `new Uint8ClampedArray(rgba)` clones into a fresh ArrayBuffer, which both
  // satisfies ImageData's no-SharedArrayBuffer type bound and detaches us from UTIF's scratch buffer.
  srcCtx.putImageData(new ImageData(new Uint8ClampedArray(rgba), width, height), 0, 0);

  const target = maxDim > 0 ? fitWithin(width, height, maxDim) : { width, height };
  let out = src;
  if (target.width !== width || target.height !== height) {
    out = document.createElement("canvas");
    out.width = target.width;
    out.height = target.height;
    const outCtx = out.getContext("2d");
    if (!outCtx) throw new Error("2D canvas context unavailable for TIFF downscale");
    outCtx.drawImage(src, 0, 0, target.width, target.height);
  }
  const blob = await new Promise<Blob | null>((resolve) => out.toBlob(resolve, "image/webp", quality));
  if (!blob) throw new Error("canvas.toBlob produced no WebP from the TIFF");
  return { blob, width: target.width, height: target.height };
}
