// GENERATED by scripts/import-voynich.mjs — one-time import of the anvil voynich-manuscript
// fixture (Beinecke MS 408). Note bodies are markdown — render via @render/svelte renderMarkdown.
// Do not edit by hand; re-run the script to regenerate.
export interface VoynichObject { id: string; source: string; label: string; width: number; height: number; }
export interface VoynichNote { objectId: string; region: [number, number, number, number]; comment: string; }
export const voynichTitle = "Voynich manuscript";
export const voynichCredits = "Voynich folios courtesy of the Beinecke Rare Book and Manuscript Library, Yale University (MS 408).";
export const voynichObjects: VoynichObject[] = [
  {
    "id": "o1",
    "source": "/voynich/article.png",
    "label": "The cipher",
    "width": 1280,
    "height": 3200
  },
  {
    "id": "o2",
    "source": "/voynich/cosmological.jpg",
    "label": "Cosmological folio",
    "width": 1600,
    "height": 2109
  },
  {
    "id": "o3",
    "source": "/voynich/herbal.jpg",
    "label": "Herbal folio",
    "width": 1143,
    "height": 1536
  },
  {
    "id": "o4",
    "source": "/voynich/balneological.jpg",
    "label": "Balneological folio",
    "width": 1536,
    "height": 1494
  },
  {
    "id": "o5",
    "source": "/voynich/script.jpg",
    "label": "Voynichese script",
    "width": 441,
    "height": 378
  }
];
export const voynichNotes: VoynichNote[] = [
  {
    "objectId": "o1",
    "region": [
      716,
      220,
      308,
      426
    ],
    "comment": "The infobox image is folio 68v — one of the cosmological diagrams. Click ahead to page 2 of this project to see the full folio."
  },
  {
    "objectId": "o1",
    "region": [
      750,
      2245,
      265,
      205
    ],
    "comment": "A herbal page reproduced in the article. The unidentified plants are among the manuscript's most-studied features. Page 3 has a higher-resolution scan."
  },
  {
    "objectId": "o1",
    "region": [
      265,
      80,
      247,
      50
    ],
    "comment": "**Voynich manuscript** — an illustrated codex written in an unknown script, carbon-dated to the early fifteenth century. The article you're looking at is itself the first page of this demo project."
  },
  {
    "objectId": "o1",
    "region": [
      768,
      2285,
      24,
      40
    ],
    "comment": ""
  },
  {
    "objectId": "o2",
    "region": [
      100,
      80,
      1400,
      1970
    ],
    "comment": "**A biological / balneological-style folio.** Despite the filename, this isn't one of the famous radial cosmological diagrams — it's a multi-zone page with a central vertical figure of nude women descending through a blue-canopied form, surrounded by paragraph-blocks of Voynichese, with a separate green herbal-like bulb at the bottom right. Pages like this dominate the manuscript's middle quires."
  },
  {
    "objectId": "o2",
    "region": [
      500,
      80,
      350,
      1070
    ],
    "comment": "**Column of nude figures.** A vertical column of small nude women is drawn inside a blue-leafed canopy, descending toward a green basin or root. The motif of stacked nymphs occurs across the manuscript's balneological / biological quires; readers have variously read this as embryology, allegorical alchemy, or a generative diagram of bodily fluids — nothing has stuck."
  },
  {
    "objectId": "o2",
    "region": [
      110,
      90,
      360,
      420
    ],
    "comment": "**Upper-left Voynichese block.** A solid paragraph of running text in the manuscript's untranslated script. Word lengths cluster in the 4-6 character range; spacing is regular; line endings show the same statistical asymmetry that researchers cite as evidence of underlying language."
  },
  {
    "objectId": "o2",
    "region": [
      900,
      1400,
      620,
      670
    ],
    "comment": "**The lower-right herbal form.** A bulbous green cabbage-like figure with small nude women clustered at its base — visually unlike the page's main top figure, more reminiscent of the herbal quire. Multi-figure pages like this blur the manuscript's quire boundaries: the categories herbal / balneological / cosmological were imposed by later scholars and don't always match how the original scribe partitioned content."
  },
  {
    "objectId": "o2",
    "region": [
      1092,
      511,
      279,
      541
    ],
    "comment": "yiugilkhli.kbbkbk"
  },
  {
    "objectId": "o3",
    "region": [
      80,
      40,
      1000,
      1440
    ],
    "comment": "**A herbal-quire folio.** A single composite plant: red sun-petalled flowers on green stems, a blue thistle-like blossom at the top, all rising from a fleshy beige tuber at the base. The drawing is folio-29-style — bold colour blocks, no botanical labels beside the parts, just a Voynichese paragraph at upper-left presumed to describe the plant. About half of the manuscript's surviving folios belong to this category."
  },
  {
    "objectId": "o3",
    "region": [
      380,
      1100,
      470,
      380
    ],
    "comment": "**The root tuber.** The whole plant rises from a fleshy beige bulb resembling a stylised potato or sweet-potato more than any European herbal exemplar. Where European herbalists drew taproots with fine lateral hairs, this one is drawn as a single rounded mass — the scribe's idea of \"root\" diverges from the medieval anatomical convention."
  },
  {
    "objectId": "o3",
    "region": [
      380,
      400,
      700,
      720
    ],
    "comment": "**The red sun-flowers.** Four near-identical blossoms with deep red petals around white-pollen centres. The repetition of the same flower across four positions is unusual for medieval herbals, which usually showed one flower per page or staged flowers at different life stages. Here all four are mature and indistinguishable — suggesting the page is illustrating the species' general appearance, not its life cycle."
  },
  {
    "objectId": "o3",
    "region": [
      80,
      90,
      500,
      510
    ],
    "comment": "**Upper-left Voynichese block.** Twelve or so lines of the manuscript's script, presumed to describe the plant — its name, uses, or preparation. Standalone glosses like this are a herbal-quire fingerprint: the running text never repeats verbatim across plants, even between visually similar ones, which argues against a copying-without-understanding theory."
  },
  {
    "objectId": "o4",
    "region": [
      50,
      30,
      1450,
      1430
    ],
    "comment": "**The rosettes foldout** (despite the filename — this isn't bathing figures, it's the famous nine-rosette diagram from the manuscript's largest fold-out leaf). Nine separate circular figures arrayed across a single sheet, connected by faintly drawn lines and rendered with patterns of dots, stars, petals, and miniature human figures. The most enigmatic page in the codex."
  },
  {
    "objectId": "o4",
    "region": [
      500,
      280,
      510,
      530
    ],
    "comment": "**The central rosette.** The largest figure on the foldout — concentric rings with a band of small bell-shaped figures around the inner disk and a label band that wraps the whole structure. Many readers have proposed it represents the centre of the cosmos, a city plan, a wind rose, or a botanical fruiting body; none of those readings has come close to consensus."
  },
  {
    "objectId": "o4",
    "region": [
      50,
      30,
      430,
      380
    ],
    "comment": "**Top-left ring with star centre.** An open ring populated by small radiating tooth-figures, with a star-burst at the centre. The ring is not labelled; the visual rhyme with star-charts has prompted some readers to call it a celestial diagram, but no positional astronomy correlates with the placement of the figures around the ring."
  },
  {
    "objectId": "o4",
    "region": [
      50,
      620,
      430,
      440
    ],
    "comment": "**Lower-left rosette with figures.** A complex circle showing what appear to be small standing figures arranged around a patterned central disk. Unlike the other rosettes on this folio, this one carries embedded human forms — a feature it shares with the balneological quire, which has led to the hypothesis that the rosettes summarise content distributed elsewhere in the manuscript."
  },
  {
    "objectId": "o4",
    "region": [
      687,
      945,
      317,
      479
    ],
    "comment": ""
  },
  {
    "objectId": "o4",
    "region": [
      null,
      null,
      null,
      null
    ],
    "comment": ""
  },
  {
    "objectId": "o4",
    "region": [
      null,
      null,
      null,
      null
    ],
    "comment": ""
  },
  {
    "objectId": "o4",
    "region": [
      null,
      null,
      null,
      null
    ],
    "comment": ""
  },
  {
    "objectId": "o5",
    "region": [
      10,
      10,
      425,
      360
    ],
    "comment": "**Voynichese — a close-up text sample.** Around 35 000 characters survive across 240 leaves, in a single distinctive hand. The script behaves statistically like a natural language (Zipf-like word frequency, syllabic structure) but no decipherment has held up to scrutiny."
  },
  {
    "objectId": "o5",
    "region": [
      5,
      20,
      55,
      340
    ],
    "comment": "**The marginal stars.** A column of small six- and eight-pointed star glyphs runs down the left margin, one per line of text. These margin-stars occur on several manuscript pages and may mark verse divisions, paragraph beginnings, or list items — their function is unsettled."
  },
  {
    "objectId": "o5",
    "region": [
      65,
      15,
      370,
      165
    ],
    "comment": "**First paragraph.** The first five visible lines show typical Voynichese: words of 4-6 characters, regular spacing, the recurring \"daiin\" pattern of three short ascenders. The first character of the paragraph is taller than its neighbours — a rubrication-style opening cap shared with Latin manuscript conventions."
  },
  {
    "objectId": "o5",
    "region": [
      65,
      210,
      370,
      160
    ],
    "comment": "**Second paragraph.** The line-end effect is visible across both paragraphs: certain glyphs cluster at line endings (notably the \"-y\" terminal) and others at line beginnings. This positional asymmetry, measurable across the full corpus, is the strongest single statistical argument for genuine language — random cipher noise wouldn't produce it."
  }
];
